// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANgypPMNVOt8z-RPaAtbetT_pRQown_fw',
    appId: '1:1058860262228:web:13f37c7c5e7a503fd89ec1',
    messagingSenderId: '1058860262228',
    projectId: 'gossipglobe-d827d',
    authDomain: 'gossipglobe-d827d.firebaseapp.com',
    storageBucket: 'gossipglobe-d827d.appspot.com',
    measurementId: 'G-97MQH4ZLPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1h5lSaCMFJRx8BvRxaRNsNyGolqU41WA',
    appId: '1:1058860262228:android:9429bbf5e35bc7a4d89ec1',
    messagingSenderId: '1058860262228',
    projectId: 'gossipglobe-d827d',
    storageBucket: 'gossipglobe-d827d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0xJ_9XIB71vxLVVLvm2A9Xb0wx5dGU_o',
    appId: '1:1058860262228:ios:dc1bc06dd2636b30d89ec1',
    messagingSenderId: '1058860262228',
    projectId: 'gossipglobe-d827d',
    storageBucket: 'gossipglobe-d827d.appspot.com',
    iosBundleId: 'com.arjun.gossipglobe',
  );
}
